[windows]
windows-pc1.example.com
windows-pc2.example.com
windows-srv2008-1.example.com
windows-srv2012-1.example.com 

[windows:vars]
 ansible_ssh_user=administrator@SKUNKWORKS.LOCAL
 ansible_ssh_pass=SecretPasswordGoesHere
 ansible_ssh_port=5986
 ansible_connection=winrm
