[windows]
windows-pc1.example.com
windows-pc2.example.com
windows-srv2008-1.example.com
windows-srv2012-1.example.com 

[windows:vars]
 ansible_ssh_user=username@example.com
 ansible_ssh_pass=MyPassword123
 ansible_ssh_port=5986
 ansible_connection=winrm
